### ISSUE TITLE
A few useful resources

### ISSUE THREAD

**Issue by westurner** [jupyter-guide/jupyter-guide#1]
- https://wrdrd.github.io/docs/consulting/data-science#tensimplerules-for-reproducible-computational-research

- https://wrdrd.github.io/docs/consulting/education-technology#jupyter-and-reproducibility

**Comment by westurner** [comment]
- Include a link to the source at the top of the notebook
- https://mybinder.org
  - https://repo2docker.readthedocs.io/en/latest/config_files.html
    - config file precedence

**Comment by pwrose** [comment]
I'm not sure what you mean by: "Include a link to the source at the top of the notebook"

**Comment by westurner** [comment]
At the top of the notebook (eg in a Markdown cell after/including the ``#
Title of the Notebook``), link to at least the e.g. the master branch of
the GitHub repo containing the notebook if not the exact .ipynb.

**Comment by westurner** [comment]
Thanks for the links. I was more expecting that links would be drawn from
said smatterings.
